### ISSUE TITLE
Always cast value to string?

### ISSUE THREAD

**Issue by Sohalt** [yogthos/config#5]
This is basically a clone of https://github.com/weavejester/environ/issues/36.
The base problem being that environment variables contain string values whereas edn-data (in config files and in lein profiles) supports other data types such as integers.
This causes inconsistent/confusing behavior when reading a value from an environment variable or edn structure.

**Comment by yogthos** [comment]
The library is deprecated in favor of [cprop](https://github.com/tolitius/cprop). However, the library doesn't intend to use the lowest common denominator when parsing the configuration data. Usually, the reason to use EDN is when you want to have complex structured configuration data.

Since it's the user decision to use EDN, it's expected  that the user would handle any mismatch between different input formats.

**Comment by Sohalt** [comment]
If the library is deprecated it would be helpful to have a depreciation notice at the beginning of the README. But thanks for clarifying.

**Comment by yogthos** [comment]
good idea, just added a notice
